spring:
  datasource:
    url: jdbc:mysql://localhost:3306/bookstore?useSSL=false&characterEncoding=UTF-8&useUnicode=true&serverTimezone=UTC&allowMultiQueries=true&allowPublicKeyRetrieval=true
    username: root
    password: 123456
    driver-class-name: com.mysql.cj.jdbc.Driver


server:
  tomcat:
    uri-encoding: UTF-8
  port: 8088


mybatis:
  mapperLocations: classpath:mapper/*.xml

